{% set name = "bazel_buildozer" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/buildtools/archive/{{ version }}.tar.gz
  sha256: e3bb0dc8b0274ea1aca75f1f8c0c835adbe589708ea89bf698069d0790701ea3
  folder: src/github.com/bazelbuild/buildtools

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }} >=1.12

test:
  commands:
    - buildozer --version

about:
  home: https://github.com/bazelbuild/buildtools
  license: Apache-2.0
  license_family: APACHE
  license_file: src/github.com/bazelbuild/buildtools/LICENSE
  summary: Buildozer is a command line tool to rewrite multiple Bazel BUILD files using standard commands.
  doc_url: https://github.com/bazelbuild/buildtools/blob/{{ version }}/buildozer/README.md
  dev_url: https://github.com/bazelbuild/buildtools

extra:
  recipe-maintainers:
    - asford
