{% set name = "bazel_buildozer" %}
{% set version = "4.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/buildtools/archive/{{ version }}.tar.gz
  sha256: 44a6e5acc007e197d45ac3326e7f993f0160af9a58e8777ca7701e00501c0857
  folder: src/github.com/bazelbuild/buildtools

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }} >=1.12

test:
  commands:
    - buildozer --version

about:
  home: https://github.com/bazelbuild/buildtools
  license: Apache-2.0
  license_family: APACHE
  license_file: src/github.com/bazelbuild/buildtools/LICENSE
  summary: Buildozer is a command line tool to rewrite multiple Bazel BUILD files using standard commands.
  doc_url: https://github.com/bazelbuild/buildtools/blob/{{ version }}/buildozer/README.md
  dev_url: https://github.com/bazelbuild/buildtools

extra:
  recipe-maintainers:
    - asford
