{% set name = "bazel_buildozer" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/buildtools/archive/{{ version }}.tar.gz
  sha256: ca524d4df8c91838b9e80543832cf54d945e8045f6a2b9db1a1d02eec20e8b8c
  folder: src/github.com/bazelbuild/buildtools

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }} >=1.12

test:
  commands:
    - buildozer --version

about:
  home: https://github.com/bazelbuild/buildtools
  license: Apache-2.0
  license_family: APACHE
  license_file: src/github.com/bazelbuild/buildtools/LICENSE
  summary: Buildozer is a command line tool to rewrite multiple Bazel BUILD files using standard commands.
  doc_url: https://github.com/bazelbuild/buildtools/blob/{{ version }}/buildozer/README.md
  dev_url: https://github.com/bazelbuild/buildtools

extra:
  recipe-maintainers:
    - asford
